language: java
before_script:
  - export MAVEN_SKIP_RC=true
env:
  - GOAL=test
  # the install_ruby_maven_when_needed can not resolve ruby-maven on travis
  - GOAL='verify -Dmaven.test.skip -Dinvoker.test=!install*
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: ./mvnw initialize
script: ./mvnw $GOAL
