language: ruby
bundler_args: --without copyright
rvm:
  - jruby
matrix:
  include:
    - rvm: jruby
      jdk: openjdk6
      script: mvn test
    - rvm: jruby
      jdk: openjdk7
      script: mvn test
    - rvm: jruby
      jdk: oraclejdk7
      script: mvn test
    - rvm: jruby
      jdk: oraclejdk8
      script: mvn test
  allow_failures:
