language: java
before_script:
  - export MAVEN_SKIP_RC=true
env:
  - GOAL=test
  - GOAL='verify -Dmaven.test.skip'
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
install: ./mvnw initialize
script: ./mvnw $GOAL
